serverName: cloudos-appstore

publicUriBase: {{APPSTORE_PUBLIC_URI_BASE}}

bcryptRounds: 8
springContextPath: classpath:/spring.xml

http:
  port: {{APPSTORE_SERVER_PORT}}
  baseUri: /

jersey:
  resourcePackages:
    - org.cobbzilla.wizard.filters.auth
    - org.cobbzilla.wizard.exceptionmappers
    - cloudos.appstore.resources
  requestFilters: [ cloudos.appstore.auth.ApiAuthFilter ]
  responseFilters: [ org.cobbzilla.wizard.filters.ScrubbableScrubber ]

database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/cloudos_appstore
  user: cloudos_appstore
  password: {{APPSTORE_DB_PASS}}

  hibernate:
    entityPackages: [ cloudos.appstore.model ]
    dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hbm2ddlAuto: validate
    validationMode: ddl

appStore:
  allowedAssetSchemes: [ http, https ]