serverName: cloudos-appstore

publicUriBase: {{APPSTORE_PUBLIC_BASE_URI}}

bcryptRounds: 8
springContextPath: classpath:/spring.xml

emailTemplateRoot: {{EMAIL_TEMPLATE_ROOT}}

emailSenderNames:
  welcome:
    fromName:  {{WELCOME_SENDER_NAME}}
    fromEmail: {{WELCOME_SENDER_EMAIL}}
  invite_to_publisher:
    fromName: {{INVITE_TO_PUBLISHER_SENDER_NAME}}
    fromEmail: {{INVITE_TO_PUBLISHER_SENDER_EMAIL}}

smtp:
  host: smtp.sendgrid.net
  port: 587
  user: {{SENDGRID_API_USER}}
  password: {{SENDGRID_API_KEY}}
  tlsEnabled: true

http:
  port: {{APPSTORE_SERVER_PORT}}
  baseUri: /

staticAssets:
  baseUri: /docs/
  assetRoot: static/
  localOverride: {{ASSETS_DIR}}
  mustacheCacheEnabled: false
  mustacheResourceRoot: static/
  utilPaths:
    INDEX_PATH: /index.html
    INDEX_ALIASES: /:/index.php
    LOCALIZE: /localize

jersey:
  resourcePackages:
    - org.cobbzilla.wizard.filters.auth
    - org.cobbzilla.wizard.exceptionmappers
    - cloudos.appstore.resources
  requestFilters: [ cloudos.appstore.auth.ApiAuthFilter ]
  responseFilters: [ org.cobbzilla.wizard.filters.ScrubbableScrubber ]

database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/cloudos_appstore
  user: cloudos_appstore
  password: {{APPSTORE_DB_PASS}}

  hibernate:
    entityPackages: [ cloudos.appstore.model ]
    dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hbm2ddlAuto: validate
    validationMode: ddl

appStore:
  allowedAssetSchemes: [ http, https ]
  appRepository: {{APPSTORE_APP_REPOSITORY}}
